# Generated by Django 6.0.1 on 2026-02-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_teacher', '0002_alter_teacher_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='card_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_teacher.bankinfo'),
        ),
    ]
