# Generated by Django 6.0.1 on 2026-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_teacher', '0003_alter_teacher_card_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
