# Generated by Django 6.0.1 on 2026-02-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_teacher', '0004_bankinfo_created_at_bankinfo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bankinfo',
            name='updated_at',
        ),
    ]
