# Generated by Django 6.0.1 on 2026-02-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_teacher', '0005_remove_bankinfo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='card_info',
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_teacher.teacher'),
        ),
    ]
