# Generated by Django 6.0.1 on 2026-02-06 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_teacher', '0006_remove_teacher_card_info_bankinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_teacher.teacher'),
        ),
    ]
